# Initial co-variates to test in models for each disease and region

# Growth anomalies Pacific -----------------------
ga_pac_vars <- c("p",
                 "Month",
                 "Median_colony_size",
                 "CV_colony_size",
                 "Poritidae_mean_cover",
                 "H_abund",
                 "SST_90dMean",
                 "Winter_condition",
                 "Hot_snaps",
                 # "BlackMarble_2016_3km_geo.1",
                 # "BlackMarble_2016_3km_geo.2",
                 "BlackMarble_2016_3km_geo.3",
                 # "Long_Term_Chl_Median",
                 # "Long_Term_Chl_90th",
                 "Long_Term_Kd_Median",
                 # "Long_Term_Kd_90th",
                 # "Long_Term_Chl_Variability",
                 "Long_Term_Kd_Variability",
                 # "Long_Term_Median_Residual",
                 # "Three_Week_Chl_Median",
                 "Three_Week_Kd_Median",
                 # "Three_Week_Chl_Variability",
                 "Three_Week_Kd_Variability"#,
                 # "Three_Week_Median_Residual"
                 )

# Growth anomalies GBR --------------------------
ga_gbr_vars <- c("Y",
                 "Month",
                 "Coral_cover",
                 "Fish_abund",
                 # "wave_mean",
                 "SST_90dMean",
                 "Winter_condition",
                 "Hot_snaps",
                 # "BlackMarble_2016_3km_geo.1",
                 # "BlackMarble_2016_3km_geo.2",
                 "BlackMarble_2016_3km_geo.3",
                 # "Long_Term_Chl_Median",
                 # "Long_Term_Chl_90th",
                 "Long_Term_Kd_Median",
                 # "Long_Term_Kd_90th",
                 # "Long_Term_Chl_Variability",
                 "Long_Term_Kd_Variability",
                 # "Long_Term_Median_Residual",
                 # "Three_Week_Chl_Median",
                 "Three_Week_Kd_Median",
                 # "Three_Week_Chl_Variability",
                 "Three_Week_Kd_Variability"#,
                 # "Three_Week_Median_Residual"
                 )

# White syndromes Pacific (Acroporidae) -------
ws_pac_acr_vars <- c("p",
                     "Month",
                     "Median_colony_size",
                     "H_abund",
                     "Parrotfish_abund",
                     "Butterflyfish_abund",
                     "Acroporidae_mean_cover",
                     # "wave_mean",
                     "Winter_condition",
                     "Hot_snaps",
                     # "Long_Term_Chl_Median",
                     # "Long_Term_Chl_90th",
                     "Long_Term_Kd_Median",
                     # "Long_Term_Kd_90th",
                     # "Long_Term_Chl_Variability",
                     "Long_Term_Kd_Variability",
                     # "Long_Term_Median_Residual",
                     # "Three_Week_Chl_Median",
                     "Three_Week_Kd_Median",
                     # "Three_Week_Chl_Variability",
                     "Three_Week_Kd_Variability"#,
                     # "Three_Week_Median_Residual",
                     # "Acute_Chla_4week",
                     # "Acute_Kd_4week",
                     # "Acute_Chla_8week",
                     # "Acute_Kd_8week",
                     # "Acute_Chla_12week",
                     # "Acute_Kd_12week"
                     # "Acute_Chla_4week_PA",
                     # "Acute_Kd_4week_PA",
                     # "Acute_Chla_8week_PA",
                     # "Acute_Kd_8week_PA",
                     # "Acute_Chla_12week_PA",
                     # "Acute_Kd_12week_PA"
                     )

# White syndreoms GBR -------------------------
ws_gbr_vars <- c("Y", 
                 "Month", 
                 "Coral_cover", 
                 "Fish_abund", 
                 # "wave_mean",
                 "Winter_condition",
                 "Hot_snaps",
                 # "Long_Term_Chl_Median",
                 # "Long_Term_Chl_90th",
                 "Long_Term_Kd_Median",
                 # "Long_Term_Kd_90th",
                 # "Long_Term_Chl_Variability",
                 "Long_Term_Kd_Variability",
                 # "Long_Term_Median_Residual",
                 # "Three_Week_Chl_Median",
                 "Three_Week_Kd_Median",
                 # "Three_Week_Chl_Variability",
                 "Three_Week_Kd_Variability"#,
                 # "Three_Week_Median_Residual",
                 # "Acute_Chla_4week_PA",
                 # "Acute_Kd_4week_PA",
                 # "Acute_Chla_8week_PA",
                 # "Acute_Kd_8week_PA",
                 # "Acute_Chla_12week_PA",
                 # "Acute_Kd_12week_PA"
                 )

