# load libraries (and install if not already installed) 

if (!require("tidyverse")) install.packages("tidyverse"); library(tidyverse)
if (!require("data.table")) install.packages("data.table"); library(data.table)
if (!require("taxizedb")) install.packages("taxizedb"); library(taxizedb)
if (!require("stringr")) install.packages("stringr"); library(stringr)
if (!require("zoo")) install.packages("zoo"); library(zoo)
if (!require("raster")) install.packages("raster"); library(raster)
if (!require("RANN")) install.packages("RANN"); library(RANN)
if (!require("ncdf4")) install.packages("ncdf4"); library(ncdf4)
if (!require("rgdal")) install.packages("rgdal"); library(rgdal)
if (!require("sf")) install.packages("sf"); library(sf)
if (!require("sp")) install.packages("sp"); library(sp)
if (!require("spatialEco")) install.packages("spatialEco"); library(spatialEco)
if (!require("rgeos")) install.packages("rgeos"); library(rgeos)
if (!require("modelr")) install.packages("modelr"); library(modelr)
if (!require("smotefamily")) install.packages("smotefamily"); library(smotefamily)
if (!require("quantregForest")) install.packages("quantregForest"); library(quantregForest)
if (!require("caTools")) install.packages("caTools"); library(caTools)
if (!require("ggplot2")) install.packages("ggplot2"); library(ggplot2)
if (!require("ggpubr")) install.packages("ggpubr"); library(ggpubr)
if (!require("ggExtra")) install.packages("ggExtra"); library(ggExtra)
if (!require("leaflet")) install.packages("leaflet"); library(leaflet)

